services:
  qdrant:
    image: qdrant/qdrant:v1.9.0
    ports:
      - "6333:6333"
      - "6334:6334"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      # Enable graceful shutdown
      QDRANT__SERVICE__GRACEFUL_SHUTDOWN_TIMEOUT: "30"
      QDRANT__SERVICE__ENABLE_GRACEFUL_SHUTDOWN: "true"
      # Ensure WAL sync for data durability
      QDRANT__STORAGE__WAL__SYNC_ON_WRITE: "false"
      # Storage path
      QDRANT__STORAGE__STORAGE_PATH: "/qdrant/storage"
      # WAL configuration
      QDRANT__STORAGE__WAL__WAL_CAPACITY_MB: "32"
      QDRANT__STORAGE__WAL__WAL_SEGMENTS_AHEAD: "0"
      # Service ports
      QDRANT__SERVICE__HTTP_PORT: "6333"
      QDRANT__SERVICE__GRPC_PORT: "6334"
      # Performance settings
      QDRANT__PERFORMANCE__MAX_OPTIMIZATION_THREADS: "4"
      QDRANT__PERFORMANCE__MAX_INDEXING_THREADS: "4"
      # Disable cluster and telemetry
      QDRANT__CLUSTER__ENABLED: "false"
      QDRANT__TELEMETRY__ENABLED: "false"
    restart: unless-stopped
    stop_grace_period: 30s

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    restart: unless-stopped

  landing-next:
    build: ./landing-next
    ports:
      - "8090:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  ingestion-service:
    build:
      context: .
      dockerfile: ingestion-service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "${MINIO_ROOT_USER}"
      S3_SECRET_KEY: "${MINIO_ROOT_PASSWORD}"
      S3_BUCKET: "${S3_BUCKET}"
      TASK_SERVICE_URL: "http://task-service:8010"
      MAX_UPLOAD_MB: "4"
      OTEL_SERVICE_NAME: ingestion-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SDK_DISABLED: "${OTEL_SDK_DISABLED}"
      OTEL_METRICS_ENABLED: "${OTEL_METRICS_ENABLED}"
    restart: unless-stopped

  embedding-service:
    build:
      context: .
      dockerfile: embedding-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      QDRANT_URL: "http://qdrant:6333"
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "${MINIO_ROOT_USER}"
      S3_SECRET_KEY: "${MINIO_ROOT_PASSWORD}"
      S3_BUCKET: "${S3_BUCKET}"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      TASK_SERVICE_URL: "http://task-service:8010"
      EMBED_MAX_CONCURRENT: "20"
      OTEL_SERVICE_NAME: embedding-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SDK_DISABLED: "${OTEL_SDK_DISABLED}"
      OTEL_METRICS_ENABLED: "${OTEL_METRICS_ENABLED}"
    restart: unless-stopped

  ai-agent-service:
    build: ./ai-agent-service
    ports:
      - "8002:8002"
    environment:
      QDRANT_URL: "http://qdrant:6333"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OTEL_SERVICE_NAME: ai-agent-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SDK_DISABLED: "${OTEL_SDK_DISABLED}"
      OTEL_METRICS_ENABLED: "${OTEL_METRICS_ENABLED}"
    restart: unless-stopped



  document-parsing-service:
    build:
      context: .
      dockerfile: document-parsing-service/Dockerfile
      args:
        PDF_PARSER_VERSION: "${PDF_PARSER_VERSION:-fast-pdf-parser-1}"
        DOCX_PARSER_VERSION: "${DOCX_PARSER_VERSION:-fast-docx-parser-1}"
    ports:
      - "8005:8005"
    environment:
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "${MINIO_ROOT_USER}"
      S3_SECRET_KEY: "${MINIO_ROOT_PASSWORD}"
      S3_BUCKET: "${S3_BUCKET}"
      LOG_LEVEL: "INFO"
      PDF_PARSER_VERSION: "${PDF_PARSER_VERSION:-fast-pdf-parser-1}"
      DOCX_PARSER_VERSION: "${DOCX_PARSER_VERSION:-fast-docx-parser-1}"
      TASK_SERVICE_URL: "http://task-service:8010"
      OTEL_SERVICE_NAME: document-parsing-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SDK_DISABLED: "${OTEL_SDK_DISABLED}"
      OTEL_METRICS_ENABLED: "${OTEL_METRICS_ENABLED}"
    depends_on:
      - db
      - minio
    restart: unless-stopped

  chunking-service:
    build:
      context: .
      dockerfile: chunking-service/Dockerfile
    ports:
      - "8006:8006"
    environment:
      TASK_SERVICE_URL: "http://task-service:8010"
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "${MINIO_ROOT_USER}"
      S3_SECRET_KEY: "${MINIO_ROOT_PASSWORD}"
      S3_BUCKET: "${S3_BUCKET}"
      OTEL_SERVICE_NAME: chunking-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SDK_DISABLED: "${OTEL_SDK_DISABLED}"
      OTEL_METRICS_ENABLED: "${OTEL_METRICS_ENABLED}"
    depends_on:
      - minio
    restart: unless-stopped

  redaction-service:
    build:
      context: .
      dockerfile: redaction-service/Dockerfile
    ports:
      - "8007:8007"
    environment:
      TASK_SERVICE_URL: "http://task-service:8010"
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "${MINIO_ROOT_USER}"
      S3_SECRET_KEY: "${MINIO_ROOT_PASSWORD}"
      S3_BUCKET: "${S3_BUCKET}"
      OTEL_SERVICE_NAME: redaction-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SDK_DISABLED: "${OTEL_SDK_DISABLED}"
      OTEL_METRICS_ENABLED: "${OTEL_METRICS_ENABLED}"
    depends_on:
      - chunking-service
    restart: unless-stopped

  data-generator:
    build: ./data-generator
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./customer_service_data:/app/customer_service_data
    profiles:
      - generate-data

  task-service:
    build: ./task-service
    ports:
      - "8010:8010"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      PARSING_SERVICE_URL: "http://document-parsing-service:8005"
      CHUNKING_SERVICE_URL: "http://chunking-service:8006"
      REDACTION_SERVICE_URL: "http://redaction-service:8007"
      EMBEDDING_SERVICE_URL: "http://embedding-service:8001"
      INDEX_DOCUMENT_SERVICE_URL: "http://index-document-service:8011"
      INDEXING_SERVICE_URL: "http://indexing-service:8012"
      OTEL_SERVICE_NAME: task-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SDK_DISABLED: "${OTEL_SDK_DISABLED}"
      OTEL_METRICS_ENABLED: "${OTEL_METRICS_ENABLED}"
    depends_on:
      - db
    restart: unless-stopped

  index-document-service:
    build:
      context: .
      dockerfile: index-document-service/Dockerfile
    ports:
      - "8011:8011"
    environment:
      TASK_SERVICE_URL: "http://task-service:8010"
      OTEL_SERVICE_NAME: index-document-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SDK_DISABLED: "${OTEL_SDK_DISABLED}"
      OTEL_METRICS_ENABLED: "${OTEL_METRICS_ENABLED}"
    depends_on:
      - task-service
    restart: unless-stopped

  indexing-service:
    build:
      context: .
      dockerfile: indexing-service/Dockerfile
    ports:
      - "8012:8012"
    environment:
      QDRANT_URL: "http://qdrant:6333"
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "${MINIO_ROOT_USER}"
      S3_SECRET_KEY: "${MINIO_ROOT_PASSWORD}"
      S3_BUCKET: "${S3_BUCKET}"
      TASK_SERVICE_URL: "http://task-service:8010"
      INDEX_MAX_CONCURRENT: "3"
      OTEL_SERVICE_NAME: indexing-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      RESOURCE_SAMPLER_ENABLED: "true"
      RESOURCE_SAMPLER_HZ: "1"
      OTEL_SDK_DISABLED: "${OTEL_SDK_DISABLED}"
      OTEL_METRICS_ENABLED: "${OTEL_METRICS_ENABLED}"
    depends_on:
      - qdrant
      - minio
      - task-service
    restart: unless-stopped

  search-service:
    build:
      context: .
      dockerfile: search-service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      QDRANT_URL: "http://qdrant:6333"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OTEL_SERVICE_NAME: search-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SDK_DISABLED: "${OTEL_SDK_DISABLED}"
      OTEL_METRICS_ENABLED: "${OTEL_METRICS_ENABLED}"
    depends_on:
      - qdrant
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector:0.99.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.5.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./observability/tempo.yaml:/etc/tempo.yaml:ro
      - tempo_data:/var/tempo
    ports:
      - "3200:3200"
    restart: unless-stopped

  mimir:
    image: grafana/mimir:2.13.0
    command: ["-config.file=/etc/mimir.yaml"]
    volumes:
      - ./observability/mimir.yaml:/etc/mimir.yaml:ro
      - mimir_data:/data
    ports:
      - "9009:9009"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana_dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - tempo
      - mimir
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_storage:
  tempo_data:
  mimir_data:
  grafana_dashboards: 